- clean: ['~']
- shell:
  - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc

- shell:
  - [type zsh || sudo apt-get -y install zsh, Install zsh shell]
  - [sudo chsh -s /bin/zsh `whoami`, Use zsh as default shell for the current user]
  - [rm -f ~/.zcompdump; compinit, Rebuild zsh completions]